version: '3.8'

name: travelgpt_infra

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: travelgpt_user
      POSTGRES_PASSWORD: travelgpt_password
      POSTGRES_DB: travelgpt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
